### ISSUE TITLE
Makefile Support

### ISSUE THREAD

**Issue by Bendodroid** [skylerlee/monokai-neo-syntax#3]
Would it be possible to add Makefile support?

The variables for example are not highlighted.

I haven't coded atom themes in the past, so my workaround below might be a stupid way to do it.
This is what I put together so far:

```less
.syntax--variable.syntax--makefile {
    color: @red;
}

.syntax--keyword.syntax--shell {
    &.syntax--operator.syntax--shell,
    &.syntax--redirect.syntax--shell {
        color: @syntax-text-color;
    }
}

.syntax--punctuation.syntax--makefile {
    &.syntax--definition {
        &.syntax--variable {
            color: @red;
        }
    }
}
```
